services:
  cyberchef:
    build:
      context: .
    image: ssqlone/cyberchef:latest
    container_name: cyberchef
    restart: unless-stopped
    expose:
      - 80
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Baku
    volumes:
      - './cyberchef:/app/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 10s
networks:
  proxy:
    external: true
